trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:

  # Azure service connection
  azureSubscription: 'dev'

  # Docker Registry service connection in Azure DevOps
  containerRegistry: 'acr'

  # Azure Container Registry
  acrLoginServer: 'acrcapacityintelligencedev.azurecr.io'

  # Docker image
  imageName: 'capacityintelligence-dev'

  # Azure Container App
  resourceGroup: 'Rg-CapacityIntelligence-Dev'
  containerAppName: 'ca-capacityintelligence-dev'


stages:

# ============================================================
# BUILD AND PUSH
# ============================================================

- stage: Build
  displayName: 'Build and Push Docker Image'

  jobs:

  - job: DockerBuildPush
    displayName: 'Docker Build and Push'

    steps:

    - checkout: self

    - task: Docker@2
      displayName: 'Docker Build and Push'
      inputs:
        command: 'buildAndPush'
        containerRegistry: '$(containerRegistry)'
        repository: '$(imageName)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(Build.BuildId)
          latest


# ============================================================
# DEPLOY TO AZURE CONTAINER APP
# ============================================================

- stage: Deploy
  displayName: 'Deploy to Container App'

  dependsOn: Build
  condition: succeeded()

  jobs:

  - job: DeployContainerApp
    displayName: 'Deploy Container App'

    steps:

    - task: AzureCLI@2
      displayName: 'Update Container App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: bash
        scriptLocation: inlineScript

        inlineScript: |

          echo "Deploying Docker image..."

          az containerapp update \
            --name "$(containerAppName)" \
            --resource-group "$(resourceGroup)" \
            --image "$(acrLoginServer)/$(imageName):$(Build.BuildId)"

          echo "======================================"
          echo "Container App deployed successfully"
          echo "======================================"

          echo "Container App URL:"

          az containerapp show \
            --name "$(containerAppName)" \
            --resource-group "$(resourceGroup)" \
            --query properties.configuration.ingress.fqdn \
            --output tsv